In [3]:
import numpy as np
import funBed as fb


HI welocome to DS


In [4]:
lst=[1,2,3.34343,4,5,6,7,8,90,0]

data=np.array(lst,dtype=int)

In [15]:
print(fb.type_collection(data))
def sample():
    """sample pgm
    """
    

<class 'numpy.ndarray'>


In [16]:
data.dtype
help(sample)


Help on function sample in module __main__:

sample()
    sample pgm



In [18]:
# For Creating all array with all values 1
onesArray = np.ones((3,4),dtype=int)
onesArray

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
zerosArray=np.zeros((3,3),dtype=float)
zerosArray
zerosArray.dtype

dtype('float64')

In [20]:
randomArray=np.random.random((2,3))
randomArray

array([[ 0.93444276,  0.77663963,  0.71064376],
       [ 0.58429234,  0.36149962,  0.57319698]])

In [21]:
# Create any zero array with values provided
emp=np.empty((3,2),dtype=float)
emp
emp.dtype

dtype('float64')

In [22]:
# Creating a full array with the value given
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [23]:
# Create an array of evenly-spaced values
np.arange(3,24,3)

array([ 3,  6,  9, 12, 15, 18, 21])

In [24]:
# Create an array of evenly-spaced values
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [31]:
my_array=np.genfromtxt('data2.txt',unpack=True,missing_values="",dtype=int,delimiter=",",filling_values=0)
my_array.dtype

dtype('int32')

In [33]:
np.savetxt('data_out1.txt',my_array,delimiter='|',fmt='%1d')
my_array.strides # tells how many bits the values are stored in memory

(4, 40)

In [ ]:
# Print the number of `my_array`'s dimensions
print(my_array.ndim)

# Print the number of `my_array`'s elements
print(my_array.size)

# Print information about `my_array`'s memory layout
print(my_array.flags)

# Print the length of one array element in bytes
print(my_array.itemsize)

# Print the total consumed bytes by `my_array`'s elements
print(my_array.nbytes)

In [42]:
#length of the array - > it relays on the numbers of cols
print(len(my_array))

3


In [43]:
# changing the() dtype of the numpy array

my_array.astype(float)

array([[ 1.,  4.,  5.,  6.],
       [ 2.,  5.,  0.,  0.],
       [ 3.,  0.,  7.,  0.]])

In [38]:
my_array1=my_array.T
my_array.shape

(10, 3)

In [37]:
my_array1.shape


(3, 10)